name = "Telepathy"
uuid = "0d7f22b2-4679-4055-8421-94b93cbff039"
license = "BSD-3"
authors = ["Marcin Koculak <koculak.marcin@gmail.com>"]
version = "0.1.0"

[deps]
EEGIO = "0b63a203-985a-4b95-9578-b702c99cc299"
